# Generated by Django 3.0.8 on 2020-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=1),
        ),
    ]
